package prueba.hibernate.pojos;
// Generated Oct 29, 2017 5:49:23 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentsId generated by hbm2java
 */
@Embeddable
public class PaymentsId implements java.io.Serializable {

	private String checkNumber;
	private int customerNumber;

	public PaymentsId() {
	}

	public PaymentsId(String checkNumber, int customerNumber) {
		this.checkNumber = checkNumber;
		this.customerNumber = customerNumber;
	}

	@Column(name = "check_number", nullable = false, length = 50)
	public String getCheckNumber() {
		return this.checkNumber;
	}

	public void setCheckNumber(String checkNumber) {
		this.checkNumber = checkNumber;
	}

	@Column(name = "customer_number", nullable = false)
	public int getCustomerNumber() {
		return this.customerNumber;
	}

	public void setCustomerNumber(int customerNumber) {
		this.customerNumber = customerNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentsId))
			return false;
		PaymentsId castOther = (PaymentsId) other;

		return ((this.getCheckNumber() == castOther.getCheckNumber()) || (this.getCheckNumber() != null
				&& castOther.getCheckNumber() != null && this.getCheckNumber().equals(castOther.getCheckNumber())))
				&& (this.getCustomerNumber() == castOther.getCustomerNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCheckNumber() == null ? 0 : this.getCheckNumber().hashCode());
		result = 37 * result + this.getCustomerNumber();
		return result;
	}

}
