package prueba.hibernate.pojos;
// Generated Oct 29, 2017 5:49:23 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name = "payments", catalog = "classicmodels")
public class Payments implements java.io.Serializable {

	private PaymentsId id;
	private long amount;
	private Date paymentDate;

	public Payments() {
	}

	public Payments(PaymentsId id, long amount, Date paymentDate) {
		this.id = id;
		this.amount = amount;
		this.paymentDate = paymentDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "checkNumber", column = @Column(name = "check_number", nullable = false, length = 50)),
			@AttributeOverride(name = "customerNumber", column = @Column(name = "customer_number", nullable = false)) })
	public PaymentsId getId() {
		return this.id;
	}

	public void setId(PaymentsId id) {
		this.id = id;
	}

	@Column(name = "amount", nullable = false, precision = 10, scale = 0)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", nullable = false, length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

}
