package prueba.hibernate.pojos;
// Generated Oct 29, 2017 5:49:23 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productlines generated by hbm2java
 */
@Entity
@Table(name = "productlines", catalog = "classicmodels")
public class Productlines implements java.io.Serializable {

	private String productLine;
	private String textDescription;
	private String htmlDescription;
	private byte[] image;

	public Productlines() {
	}

	public Productlines(String productLine) {
		this.productLine = productLine;
	}

	public Productlines(String productLine, String textDescription, String htmlDescription, byte[] image) {
		this.productLine = productLine;
		this.textDescription = textDescription;
		this.htmlDescription = htmlDescription;
		this.image = image;
	}

	@Id

	@Column(name = "productLine", unique = true, nullable = false, length = 50)
	public String getProductLine() {
		return this.productLine;
	}

	public void setProductLine(String productLine) {
		this.productLine = productLine;
	}

	@Column(name = "textDescription", length = 4000)
	public String getTextDescription() {
		return this.textDescription;
	}

	public void setTextDescription(String textDescription) {
		this.textDescription = textDescription;
	}

	@Column(name = "htmlDescription", length = 16777215)
	public String getHtmlDescription() {
		return this.htmlDescription;
	}

	public void setHtmlDescription(String htmlDescription) {
		this.htmlDescription = htmlDescription;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
